export enum CategoriaItem {
  ALIMENTO = 'ALIMENTO',

  ACESSIBILIDADE = 'ACESSIBILIDADE',

  ELETRODOMESTICO = 'ELETRODOMESTICO',

  FERRAMENTAS = 'FERRAMENTAS',

  HIGIENE = 'HIGIENE',

  INFANTIL = 'INFANTIL',

  INFORMATICA = 'INFORMATICA',

  LIMPEZA = 'LIMPEZA',

  LIVROS = 'LIVROS',

  MONETARIO = 'MONETARIO',

  MOVEIS = 'MOVEIS',

  PAPELARIA = 'PAPELARIA',

  SAUDE = 'SAUDE',

  UTILITARIO = 'UTILITARIO',

  VESTUARIO = 'VESTUARIO',
}
